using System;
using System.Linq;

namespace AoC.Year2018.Day2
{
    public class Part2 : BasePart
    {
        protected void RunScenario(string title, string input)
        {
            RunScenario(title, () =>
            {
                var lines = input.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);

                // assuming the inputs are always the same length
                // LINQ from-from is like a cross-join in SQL
                var q = (from i1 in lines
                        from i2 in lines
                        where i1 != i2
                        let common = Common(i1, i2)
                        // this is a match if the shared parts is exactly one character less than the inputs
                        where common.Length == i1.Length - 1
                        select common
                    ).ToArray();

                Console.WriteLine(q.Length);
                Console.WriteLine(q[0]);
            });
        }

        private string Common(string i1, string i2)
        {
            // return a string with *only* the shared parts of the two strings
            return new String(i1.Zip(i2, (x1, x2) => x1 == x2 ? x1 : ' ').Where(i => i != ' ').ToArray());
        }

        public override void Run()
        {
            RunScenario("initial", @"abcde
fghij
klmno
pqrst
fguij
axcye
wvxyz");
            //return;
            RunScenario("part1", @"wkzhyfdpluzeqvajtbbosngkxc
wrzhyfdplumeqvajtbioskfksc
wrzhyfdolumyqvajtbiosngkxs
urzhyfdplbmeqvrjtbiosngkxc
wrzhyfrulumeqvajtbiosngkxf
wrzhnfdprumvqvajtbiosngkxc
wrzhyfpplumeivajtbiosrgkxc
wrzhybdplumeqvaftbiosxgkxc
wrzgyfdplumeqvaltbiosngcxc
wrzhbfdzlumeqvajtbipsngkxc
wrzhyfdplumwqeajtbiosngxxc
wrzhyddplumeqvajtbimsngkxo
wrzhyfdplumsqdajtfiosngkxc
wrzvyfdplumeqjajtbkosngkxc
wrzhyfddlumeqvujtbiosngxxc
nrzhywdplumeqvajtbtosngkxc
wzzhyfdplomeqvdjtbiosngkxc
urzhyfdplumeqvaatbiosngkxb
wtzyyfdplumeqvajtbiosngkxl
wrzhyfdhlumnqvajebiosngkxc
wrzhyfdplumpqvajtbiosnyjxc
wrzdyfdplumeqvajtviospgkxc
wrzhyfdplzmeqvajtbiosegfxc
wrzhyfdglumkqvajtwiosngkxc
wrzhtfdplgmeqvaqtbiosngkxc
wrzhyfdplumeqvajxpiosngexc
frzhyfdplvmeqvajtbiosngkxp
wrzhyfkplumeqvajtbfosngkpc
irzhyfqplumeqvajtbiosngktc
wrzhyfdpluvoqvajtbioingkxc
wrzhyfdplumemvautbuosngkxc
wfzhyflplumeqvijtbiosngkxc
wrzhyfdglumeqvzjkbiosngkxc
wrzcyfdplaneqvajtbiosngkxc
wrzhbfdplumeqwajtbiosngpxc
szdhyfdplumeqvajtbiosngkxc
krzhyfdplumeqvajtxilsngkxc
brzhyfmplumexvajtbiosngkxc
wrzhyvdplumeqvajtbiosiglxc
orzhyfdplumeqvaotbcosngkxc
hrzhyfdplumeqvaptbiocngkxc
wwzhyfdklummqvajtbiosngkxc
wrzhyfdppymeqvvjtbiosngkxc
wsehyudplumeqvajtbiosngkxc
wrzhyzpplumeqvajtbioscgkxc
wrzhyfqpyumeqvajtbiusngkxc
urzhyfdpdumeqmajtbiosngkxc
wrzhyfdrlumxqvajtbiosnakxc
wrthyfdplumeskajtbiosngkxc
wrzhyfdplymeqvajtbiesbgkxc
wrzhyfdqlumeqyajtciosngkxc
trzhsfdplumeqyajtbiosngkxc
wpzhyfdplimeqvajtbiosngfxc
wrzhhfdplrmeqvajtbiosngkxx
wrzhycdpgumeqvajtbioslgkxc
wrzhyfdelumeqvajgtiosngkxc
wrzhyfdplutebvajtbiosygkxc
wrzhyfdplukeqvajtbiorngkec
erzhyfdilumeqvajwbiosngkxc
wrzhyfdplumnivxjtbiosngkxc
wrzhyfdplumebvajtoiovngkxc
wrzhyfdplumeqvajtbtosnwkxe
wrzhyfxplumevvajtciosngkxc
wbzhyfdxlumeqvajtriosngkxc
wrzyyfdplumeqvajmbiosngkxb
wfthyfdplumeqvajtbiosngkdc
wrzhuedplumeqvajtbgosngkxc
wrzhifdplumeqvajtsrosngkxc
wrzhyfdplumqqvajtaiosngkac
krzhyfvvlumeqvajtbiosngkxc
wrzhyfdplzmeqqajtbiosngkvc
wrzhyfqplumeqvajtbiosngdxy
wrzhyfdpluieqvajtbiosngjjc
wrzhyfdvlumeqrajdbiosngkxc
wrzhcfdpxumeqvajtbiotngkxc
wrzhyfdprumeqvaitbiosngexc
wrzhygdplumeqvpjtbiasngkxc
wrzhyndplumeqvajtpiosngkoc
wrzhyfdplumedvajtriowngkxc
wezjyndplumeqvajtbiosngkxc
wrmhyfdplumewiajtbiosngkxc
wrztyfdplumeqnajtbiobngkxc
wrzhyfdpyumeqvajjbijsngkxc
wrfhyfdplumeqkajtbiosnqkxc
wrzhyfdpllmezvartbiosngkxc
wszhyfdplumeqeajtbiqsngkxc
wrzhyfdplumeqwajtbnosnikxc
wrzvyfqulumeqvajtbiosngkxc
drzhyfdplureqvajtbiqsngkxc
wrzhyfdplumeqjamtbigsngkxc
wrzhyfdplumeqvajbbiosngzrc
grzhyfdpuumeqvajtbicsngkxc
wrrhyfdplumeqvajtgiosnggxc
wrzhyfkplumvqvajtbiosnhkxc
wrzhyfdplumeqvajtbicspgkxa
wrzhyfdplumeqvajtiiosnggoc
wfzhyfdplumyqvaytbiosngkxc
wrzhyfdpcumeqvajtbibsnfkxc
wrzhyfdplumeqvajtbigsnzkmc
wrzhyfdplcmeqvqjtriosngkxc
wrzhypdplwmeqvajtbiosnvkxc
wrziyfdmlumeqvaatbiosngkxc
wkzhyfdplsmeqvajobiosngkxc
wrzhyfdplumeqvkjvliosngkxc
wzzbyfdplumeqvajtbiolngkxc
wrzhyfdplvweqvajtbipsngkxc
wrzhyvdplumeqvujtbiosnfkxc
wrbhyfdplumedvajtbiosnhkxc
wrzhofdplumeqvajtbiosnskxy
wrzhyfdplumeqvaetbiohwgkxc
wezhyfoplumeqvajtbiosngmxc
wrzhykdblumeqvajtbiosngkjc
wrzhyddplwmeqvajtbioungkxc
wrzhyldplumqqvajpbiosngkxc
wrzhyfdtlumeqvajtbiusngkcc
wrzhyfdilumeqvajtbiosdgkxk
wrvhywdplumeqvajtbiosngoxc
wrzhyfdpyumeqvajtkiomngkxc
wrzhyfdpbummqvajtbiosngcxc
wrzhyfdpljmeqvajlbiosngjxc
wrzhyfdpmuieqdajtbiosngkxc
wrzgrfdplumeqvaktbiosngkxc
wrzhgrdpluueqvajtbiosngkxc
wazhyfdplhmeqvaqtbiosngkxc
wruhyfdplumeqvujtliosngkxc
wrzvyfdslumeqvajtbiwsngkxc
wrzhyfdplumeivactbiosqgkxc
wrzpyfdpbumeqvajtbioszgkxc
bgzhyfdplumeyvajtbiosngkxc
wrzhyfkplumeqvajtbiotngkxh
wrdhyfhplumexvajtbiosngkxc
brzhyfdpgumeqvgjtbiosngkxc
arzhqfdpeumeqvajtbiosngkxc
wrzhyftplumeqvajfbiosnykxc
wrzhyfdpcumeqvartbtosngkxc
wrzhvfzplumdqvajtbiosngkxc
wrzhyfdjlumeqvaetbiosjgkxc
wrbhyfdplumeqvajjjiosngkxc
wrxhyfdplumeqvajtbiyskgkxc
wpzhyydplumeqvajtbiosqgkxc
wrzhyfdplumzqvajtbzoongkxc
crzhyfdplnmeqvajtbjosngkxc
wrzhyfdpluveusajtbiosngkxc
wrzhypdpluyecvajtbiosngkxc
wrnhyfdplumeqvajtbioengoxc
wrzhypdplumefvajybiosngkxc
wrzhyfdplumeqvattviosngkdc
wrzhyfdplqmeqbajtbiostgkxc
wrghyfdpluveqvajtbiosngkxn
wryhyfdplumeqvajrbiopngkxc
wrzhyqdplumeqvajtbiwsngkxt
wrmoyfdpluheqvajtbiosngkxc
wrghyfdnlumeqvyjtbiosngkxc
wrzpyfdplumevvaatbiosngkxc
wrzhyfdplumhqvajtbiodngxxc
wrzhyfdplumeqcajtbioyjgkxc
wrzhyfdplumeqvajabirsngkgc
wrzhtfnplukeqvajtbiosngkxc
wqzhyfdplumeqvajtbiopegkxc
lrzhzfdplumeqdajtbiosngkxc
wrzzyfdplumeqvajnkiosngkxc
wrzhyfdflmmeqvajmbiosngkxc
wrzoyfdplumeqvjjtpiosngkxc
wrzhyfdpmpmeqvajhbiosngkxc
krvhyfdplumeqvajtbiossgkxc
wrzhyfdplumeqvaetviosnmkxc
wrzhyfzclumeqvajtbiosngwxc
wrzhyfdpvumeqvajtbiosngkcv
wrzhyfdpoumeqvajtbiozngoxc
wrzhyfwglumeqvajtbxosngkxc
wrshyfdplumeqiajtbiosngklc
wrzhyfdptdmeqvajtziosngkxc
wrwhyfdplumeqqajtbiosngkxj
wrzlyfypldmeqvajtbiosngkxc
wrzhyfdplumeqvajtbirknikxc
wrzhyhdplumeqvajtbmosnbkxc
wyzhyfiplumeqvwjtbiosngkxc
wrzgyfsplumeqvajtziosngkxc
wrzhrfdllumepvajtbiosngkxc
wrzayfdplumeqvajtbiosqgktc
whzhyfdplemnqvajtbiosngkxc
wazhyfdplumeqvaptbioongkxc
wrzhyfdpluueqvajtbiosnglvc
wrzhyfdplumjqvajmbionngkxc
wrzhofdplvmeqvajtbiosnqkxc
wrzhfidpluzeqvajtbiosngkxc
wrzhlfdpcumeqvaatbiosngkxc
wrzhyfdplumewvajtbiosigkoc
wrzjyfdplwmeqvajtbiodngkxc
wrzhyfdplumeqnsjtniosngkxc
wrzxyfdplxmeqvajtbiosngkdc
wrzhyfdplumpqvartbuosngkxc
orzhyfdplumeqzsjtbiosngkxc
wrzhyfdplumebvawtbiosngkxt
wrztyfdulumeqvajtbiosngkxy
wrzhytdplumeqvajtbznsngkxc
wrzhvfdplumeqvajtbinsngkxu
wezmyfdplumeqvajhbiosngkxc
wrzhhftplumeqvajtaiosngkxc
wrzhyfgplumeqvajtbioskgjxc
ujuhyfdplumeqvajtbiosngkxc
wryhymdplumeqvaftbiosngkxc
wrzhygdplumeqvajibiosfgkxc
frzhyfdppumeqvavtbiosngkxc
wruhyfdylumeqvajzbiosngkxc
wrzhzfdplumeqvajtbwosygkxc
wrzhyfdplumeqvaeteiojngkxc
wrhhyfdplumeqvajtiiopngkxc
irzhyfdplumeqvajtbiosngryc
wrvhycdpzumeqvajtbiosngkxc
wrzhyfdplumyqwajtboosngkxc
wrzthfdplumeqvajtbioengkxc
mrzhyfdalumeqvajtbiosngcxc
wrzhyfdflumpqvajtbiosngkmc
wrzhyfxplumeqvajtbiosnvkxo
wrzhyfdglumeqvajtbiosnfkxu
wrzhyfdnrumeqpajtbiosngkxc
wrzhlipplumeqvajtbiosngkxc
wrzhkfdplumemvajtbiohngkxc
wrziyfdmlumeqvaatbiosngkoc
wrzhyfdplwceqvajtbiosngzxc
wrzhyfdplumpqvactbiosngixc
wdzhyfdhdumeqvajtbiosngkxc
wnzhyfdplumeqvajtbbosngrxc
wrzhyfdblumeqvajtbiosngvxw
wyzhyfxpkumeqvajtbiosngkxc
wrzhywdplumjqvajgbiosngkxc
wrzhyfdpxumhqvajtbiokngkxc
wrzhxfpplumeqvajtbiosngkxk
mrzhyfdplumeqkajubiosngkxc
drzhyfdplumeqvajtbioingnxc
wrekyfdplumeqvajtbidsngkxc
wrzhyfdplumeanyjtbiosngkxc
wrzhyddpluzeqvajtbiosngtxc
wrzfyfdplumeqvaqtbiosngkxr
wrghywdpluneqvajtbiosngkxc
wrzhyfdplueeqvaptbioyngkxc
wrzhyqdpllmeqvajtbiosngdxc
whzhyfdxlumeqvajtbiosngksc
wrzjyfdplumeqvuitbiosngkxc
brzhyfdplumeqhajtbiolngkxc
wrzhyfqclureqvajtbiosngkxc
wwzhpfdplureqvajtbiosngkxc
wrzhyfdplumeqvavebijsngkxc
wrzhyfdpuumeqvajtsiosnkkxc
wrxhyfuplumeqvajtbiosngpxc
wrzhyfdplumeqvujlbiospgkxc
wrzvyfdplumeqvajtbiwsngpxc
wrzhyndplumeqvajtbiwsnekxc
wrzhkfdpoumeqvautbiosngkxc");

        }
    }
}
